name: test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Show branch name
        run: |
          echo ${{ steps.extract_branch.outputs.name }}

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.release_tag.outputs.version }}'