name: create images only when ./test is changed

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: verify test dir changed
        id: verify-test-dir-changed
        run: |
          echo ::set-output name=test-output::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- ./test )

      - name: Say Goodnight Kevin
        if: ${{ steps.verify-test-dir-changed.outputs.test-output }}
        run: |
          echo "Goodnight Kevin"