name: test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: |
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
          echo "::set-output name=patch_version::${GITHUB_REF/refs\/tags\//}"

      - name: Show branch name
        run: |
          echo ${{ env.GIT_TAG }}
          echo "${{ steps.extract_branch.outputs.patch_version }}"

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.extract_branch.outputs.patch_version }}'