name: create images only when ./test is changed

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    if: ${{ git diff ./test }}
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodnight Kevin
        run: |
          echo "Goodnight Kevin"