name: create images only when ./test is changed

on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: verify test dir changed
        id: verify-test-dir-changed
        uses: tj-actions/verify-changed-files@v9
        with:
          files: |
            test

      - name: Say Goodnight Kevin
        if: contains(steps.verify-test-dir-changed.outputs.changed_files, 'test')
        run: |
          echo "Goodnight Kevin"