name: tag on branch push

on:
  push

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo at latest
      uses: actions/checkout@v2

    - name: Install required packages
      run: go get -u ./...
      
    - name: Run script
      id: test-output
      run: ./.github/workflows/test.sh -n qa -m ${{ github.event.head_commit.message }}
