name: tag on branch push

on:
  push

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo at latest
      uses: actions/checkout@v2

    - name: Install required packages
      run: go get -u ./...
      
    - name: Build binaries for archive
      id: build-prod
      run: go build

    - name: Archive binaries
      id: archive-prod
      run: zip -r artifact.zip /home/runner/work/test-actions

    - name: Bump and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      id: create-release
      if: steps.tag_version.outputs.new_tag != ''
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: /home/run/work/test-actions/artifact.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    
