name: tag on branch push

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo and Tag History
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install Required Packages
        run: go get -u ./...

      - name: Bump and Tag Prerelease Versions
        id: tag_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "feat"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          short_tags: false
          bump_each_commit: false

      - name: reserve tag
        id: reserve_tag
        run: git tag ${{ steps.tag_version.outputs.version }}

      - name: try it again
        id: try_again
        run: git tag ${{ steps.tag_version.outputs.version }}

      - name: See Error
        if: ${{ failure() }}
        run: echo ${{ steps.tag_version.outputs.version }}   
