name: tag on branch push

on:
  push

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo at latest
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Install required packages
      run: go get -u ./...

    - name: Bump and tag
      id: tag_version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "feat"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        short_tags: false
        bump_each_commit: false

    
