name: tag on branch push

on:
  push

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo at latest
      uses: actions/checkout@v2

    - name: Install required packages
      run: go get -u ./...
      
    - name: Build binaries for archive
      id: build-prod
      run: go build

    - name: Archive binaries
      id: archive-prod
      run: pwd
      #run: zip -r artifact.zip ./qtroller

    - name: Run script
      id: version-script
      run: ./.github/workflows/test.sh -m ${{ github.event.head_commit.message }}

    - name: Tag
      id: autotagger
      if: steps.version-script.outputs.new_tag != ''
      run: |
        git tag -a ${{ steps.version-script.outputs.new_tag }} -m ${{ github.event.head_commit.message }}
        git push origin ${{ steps.version-script.outputs.new_tag }}

    - name: Release
      id: create-release
      if: steps.autotagger.outputs.tagname != ''
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./qtroller/artifact.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    
