name: "Lint PR Title"

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

permissions:
    pull-requests: read

jobs:
    lint-title:
        name: Lint PR Title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                types: |
                  chore  
                  feat
                  fix
                  hotfix
                  revert
                  test
                scopes: |
                  CRM
                  ID
                  Lib
                  Sales
                  Search
                  Repo
                requireScope: true